spring.application.name=government-subsidy-system-h2
server.port=8080

# H2 Database with MySQL Mode


spring.datasource.url=jdbc:mysql://localhost:3306/subsidy_db
spring.datasource.username=root
spring.datasource.password=Root@123

# Disable automatic SQL script initialization (Hibernate manages schema)
spring.sql.init.mode=never

# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# JWT Security
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# File Upload
app.upload.dir=uploads/documents
app.scheduling.enabled=true
